### ISSUE TITLE
../chat/playground 에서 AssertionError: Feedback token task was not created. 에러가 발생합니다. ㅜ

### ISSUE THREAD

**Issue by normalstory** [teddylee777/langserve_ollama#2]
테디님 안녕하세요! 
올려주신 영상들 잘 보고 있습니다! 

영상을 보며 공유해주신 코드를 실행해봤는데요;;
http://0.0.0.0:8000/prompt/playground/
http://0.0.0.0:8000/translate/playground/
http://0.0.0.0:8000/llm/playground/
세 곳에서는 테디님 유튜브 영상과 동일한 결과가 출력됩니다. 

그런데..  
http://0.0.0.0:8000/chat/playground/
으로 접속한 경우에만 아래와 같은 에러가 나고 있습니다. 
혹시 컴퓨터 환경에 따라 별도로 추가해야 할 세팅이나 설정 값이 있을까요? 
*참고로 Mac(venv, Python 3.10.7) 사용 중입니다.

```
INFO:      - "GET /chat/c/N4XyA/input_schema HTTP/1.1" 200 OK
INFO:      - "POST /chat/stream_log HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/chanwoo/code/langserve_ollama/st/lib/python3.10/site-packages/sse_starlette/sse.py", line 282, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/Users/chanwoo/code/langserve_ollama/st/lib/python3.10/site-packages/sse_starlette/sse.py", line 271, in wrap
    await func()
  File "/Users/chanwoo/code/langserve_ollama/st/lib/python3.10/site-packages/sse_starlette/sse.py", line 221, in listen_for_disconnect
    message = await receive()
  File "/Users/chanwoo/code/langserve_ollama/st/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 535, in receive
    await self.message_event.wait()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 1073a7d90

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/Users/chanwoo/code/langserve_ollama/st/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |   File "/Users/chanwoo/code/langserve_ollama/st/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
  |     return await self.app(scope, receive, send)
  |   File "/Users/chanwoo/code/langserve_ollama/st/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/Users/chanwoo/code/langserve_ollama/st/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/Users/chanwoo/code/langserve_ollama/st/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
  |     raise exc
  |   File "/Users/chanwoo/code/langserve_ollama/st/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/Users/chanwoo/code/langserve_ollama/st/lib/python3.10/site-packages/starlette/middleware/cors.py", line 93, in __call__
  |     await self.simple_response(scope, receive, send, request_headers=headers)
  |   File "/Users/chanwoo/code/langserve_ollama/st/lib/python3.10/site-packages/starlette/middleware/cors.py", line 148, in simple_response
  |     await self.app(scope, receive, send)
  |   File "/Users/chanwoo/code/langserve_ollama/st/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/Users/chanwoo/code/langserve_ollama/st/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/Users/chanwoo/code/langserve_ollama/st/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/Users/chanwoo/code/langserve_ollama/st/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/Users/chanwoo/code/langserve_ollama/st/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
  |     await route.handle(scope, receive, send)
  |   File "/Users/chanwoo/code/langserve_ollama/st/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
  |     await self.app(scope, receive, send)
  |   File "/Users/chanwoo/code/langserve_ollama/st/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "/Users/chanwoo/code/langserve_ollama/st/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/Users/chanwoo/code/langserve_ollama/st/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/Users/chanwoo/code/langserve_ollama/st/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
  |     await response(scope, receive, send)
  |   File "/Users/chanwoo/code/langserve_ollama/st/lib/python3.10/site-packages/sse_starlette/sse.py", line 268, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/Users/chanwoo/code/langserve_ollama/st/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/Users/chanwoo/code/langserve_ollama/st/lib/python3.10/site-packages/sse_starlette/sse.py", line 271, in wrap
    |     await func()
    |   File "/Users/chanwoo/code/langserve_ollama/st/lib/python3.10/site-packages/sse_starlette/sse.py", line 251, in stream_response
    |     async for data in self.body_iterator:
    |   File "/Users/chanwoo/code/langserve_ollama/st/lib/python3.10/site-packages/langserve/api_handler.py", line 1250, in _stream_log
    |     raise AssertionError("Feedback token task was not created.")
    | AssertionError: Feedback token task was not created.
    +------------------------------------
```

**Comment by chj2812** [comment]
저도 너무 도움을 많이 받고 있습니다. 이상하게 /chat/playground 에서만 그러는데, 혹시 해결되셨을까요?

**Comment by normalstory** [comment]
@chj2812 님도 그러시군요!! ㅜ 개인적으로,, 여기저기 유명하다는 code전용 llm을 실행해가면서 원인을 찾고 있는데 ㅜ 아직 해결하지 못했습니다..

**Comment by teddylee777** [comment]
`LANGCHAIN_API_KEY` 가 혹시 설정이 되었는지 한 번 확인해 보시겠어요?

아래는 `.env` 설정의 예시입니다.

LANGCHAIN_TRACING_V2=true
LANGCHAIN_ENDPOINT=https://api.smith.langchain.com
LANGCHAIN_API_KEY=이곳에 LANGCHAIN API KEY 입력
LANGCHAIN_PROJECT=MY_LANGSERVE_PROJECT

**Comment by normalstory** [comment]
오! @teddylee777 ! 고맙습니다!! 

**1. 바로 적용해보았습니다!** 
공유된 문서 중.. 일단,, server.py에 아래 코드를 추가해서 확인해봤습니다..
```
# 관련 키 로드하기 
from dotenv import load_dotenv
load_dotenv()

# 로드 상태 확인하기 
SECRET_ENV = os.getenv("LANGCHAIN_API_KEY")
print(SECRET_ENV)

```
하지만.. -> 정상적으로 로드된 것을 확인했지만 결과는 동일했습니다. 


**2. 혹시 몰라서 '브라우저 개발자 모드'도 확인해봤는데..**
`A form field element has neither an id nor a name attribute. This might prevent the browser from correctly autofilling the form.
To fix this issue, add a unique id or name attribute to a form field. This is not strictly needed, but still recommended even if you have an autocomplete attribute on the same element.`
![스크린샷 2024-04-21 오전 1 51 30](https://github.com/teddylee777/langserve_ollama/assets/1615995/abed1430-0c6a-41e0-8885-4fb5da9a3f45)



3. 무슨 내용인가 찾아보니..
VSCODE확장-CodeGPT(GPT-4)에게 물어보니...
```
_해당 에러 메시지는 양식 필드가 id나 name 속성을 가지지 않아서 나오는 문제입니다.
간단히 말해, 브라우저는 다음에 이 페이지가 로드될 때 필드를 올바르게 자동 완성하기 위해 이러한 속성을 사용합니다. 또한 이는 양식 제어(예: label)과 양식 필드 사이의 연결에도 사용되어, 접근성을 향상시킵니다.
아래와 같이 id 속성 또는 name 속성을 추가하면 이 문제를 해결할 수 있습니다._ 

<input type="text" id="myField" />
<!-- or -->
<input type="text" name="myField" />


_제공해주신 코드는 파이썬으로 작성되었으며 FastAPI를 사용하여 웹 애플리케이션을 실행하고 있습니다. 이 코드는 백엔드 로직을 처리하며, "A form field element should have an id or name attribute"라는 오류는 프론트엔드 영역, 구체적으로 HTML form 필드와 관련이 있는 문제입니다.
따라서 이 문제는 파이썬 코드를 수정하여 해결할 수 있는 문제가 아니라 프론트엔드 코드를 수정해야 하는 문제입니다.
HTML 입력 필드에 'id' 또는 'name' 속성의 추가는 프론트엔드 코드의 범위에 있으며 HTML, CSS, JavaScript 같은 프론트엔드 기술을 사용하는 파일에서 수정해야 합니다. 현재 제공된 파이썬 코드에서는 이를 처리할 수 없습니다.
혹시 자동 생성된 HTML 코드를 사용하거나 FastAPI의 자동 문서 생성 기능 등으로 HTML 코드를 다룬다면 그것의 방식이나 설정을 살펴보시는 것이 좋을 것입니다._
```
라고 합니다. 물론 환각일 수도 있지만.. ㅜㅜ 내일까지 못찾으면.. 랭체인 오피셜에도 한번 이슈를 남겨볼까 생각 중입니다. ;;

**Comment by teddylee777** [comment]
혹시 그럼 localhost 에서 playground 는 잘 실행이 되는지 한 번 확인해 보실 수 있으세요~?

**Comment by normalstory** [comment]
../prompt/playground/     
../translate/playground/   
../llm/playground/               
http://0.0.0.0:8000과 .ngrok-free.app 모두 잘 돌아갑니다.. 

../chat/playground/만 안되는 거 같아요 ㅜ

**Comment by teddylee777** [comment]
아 localhost 에서 올리셨을 때도 /chat/playground/ 가 안된다는 말씀이시군요.. 
혹시 원본 코드에서 변경하신 부분이 있을까요?

**Comment by normalstory** [comment]
@teddylee777님!! ..먼저 주말 늦은시간까지 답변 주셔서 너무 감사드립니다!! 감동입니다ㅜ 
_(죄송하기도하고요 ㅜ 아마 컴퓨터 설정 이슈인 것 같기도해서 .. ㅜ 제가 조금 더 찾아보겠습니다)_

1. **태디님 깃헙 클론뜬 원본**으로 디버깅 중입니다
- 개인적으로 쓰던 코드는 일단 드롭해두고 원본 베이스로 원인을 찾고 있습니다.

2. 랭스미스에서 로그를 확인 중
- 신기하게 여기서는 정상적으로 회신을 하고 있어요!! ㅜ 어찌된걸까요? ㅜ 
- 그래서 단도직입적으로다가... chat gpt에게 **"너 왜그러냐"**고 물어봤습니다. ㅋ
<img width="1267" alt="스크린샷 2024-04-21 오전 1 48 35" src="https://github.com/teddylee777/langserve_ollama/assets/1615995/61b15ddf-a2da-4584-b910-a5c9cdda5813">



3. chat gpt본인? ;) 이 uvicorn이 원인인거 같다고 하니..  
- 다른 os와 다른 pc에서도 한번씩 더 확인해보고 관련 결과가 나오는데로 추가로 업데이트 남기도록 하겠습니다.


늦은 시간까지 회신 남겨주셔서,,, 다시한번 고맙습니다!!

**Comment by teddylee777** [comment]
간단한 원인 일 것 같아서요~^^
혹시 ngrok 실행되어 있는 상태에서 제가 접속해서 한 번 봐도 될까요?

**Comment by normalstory** [comment]
오! 그럼요!! 
https://7268-221-147-182-251.ngrok-free.app/prompt/playground/ 입니다~~~


아;; 참고로 인스펙터에서 보니... EOF가 떴어요~ :(
<img width="1202" alt="스크린샷 2024-04-21 오전 1 47 43" src="https://github.com/teddylee777/langserve_ollama/assets/1615995/24e241c2-eaac-427c-a6aa-b00f87887eb2">

**Comment by teddylee777** [comment]
저도 브라우져에서는 마찬가지로 동작을 안했는데요 ㅠ

코드로 돌려보니 정상 동작을 하더라고요.
Ollama 에는 문제가 없는 것 같고요. LangServe 쪽 오류일 것 같아요!
이건 LangServe 쪽에 issue 한 번 등록해 봐야 할 것 같아요.
아직 초기라 버그가 있을 수 도 있을 것 같습니다!

![capture-20240421-010712](https://github.com/teddylee777/langserve_ollama/assets/10074379/435c1571-56fa-4f0c-8f65-78f7ba5daa28)

**Comment by teddylee777** [comment]
도움이 되지 못해 죄송합니다. 혹시 나중에 해결 되면 알려주세요! 저도 한 번 검색해 볼께요^^

**Comment by normalstory** [comment]
별말씀을요!! 늦은 시간까지 너무 감사드려요! 
추가로 변경사항이나 해결되면 바로 업데이트 코멘트 남기겠습니다~ 

아! 아시죠?!  태디님 영상보고 늘 많이 배우고 자극받고 감사하고 있습니다~  
늘 고맙습니다~ 안녕히 주무세요!

**Comment by teddylee777** [comment]
@normalstory 님 응원의 말씀 감사합니다. 앞으로도 도움이 될 수 있는 좋은 콘텐츠 열심히 제작하겠습니다! 평안한 밤 되세요!! 감사합니다.

**Comment by chj2812** [comment]
@teddylee777 님, 정말 감사드립니다. @normalstory 님과 대화하신 내용 보고, 이것저것 시도해 보도록 하겠습니다. 
늦은 밤까지 테디님 정말 대단하세요~ 그리고 @normalstory 님도 파이팅입니다. 저 같이 아무것도 모르는 초보가 이해할 수 있는 콘텐츠를 만드는 게 얼마나 힘든 일인지...... 정말 감사드립니다.

앞으로도 꾸준히 시청하며, 열심히 배우겠습니다.
항상 감사드리고, 즐거운 주말 보내시기 바랍니다.

**Comment by chj2812** [comment]
이게 맞는지는 모르겠지만, @teddylee777 께서 제공하신 /app/chain.py을 다음과 같이 수정해 보았습니다.

prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            "You are a helpful AI Assistant. Your name is 'choi'. You must answer in Korean.",
        ),
        #MessagesPlaceholder(variable_name="messages"),
        MessagesPlaceholder(variable_name="chat_history"),
        ("human","{text}"),
    ]
)

그런 다음, server.py도 다음과 같이 수정했습니다.

add_routes(
    app, 
    chain, 
    path="/chat",
    playground_type="chat"
)

이렇게 했더니, /chat/playground가 제대로 되더라구요.
제가 초보라서, 맞게 한 것인지는 모르겠습니다. @teddylee777 님과 @normalstory 님의 설명이 필요한 부분입니다.
성공은 했는데, 뭐 때문에 되는 건지를 모르겠습니다...ㅠㅠ

**Comment by teddylee777** [comment]
@chj2812 님 공유 감사합니다.
@normalstory 님께서 저렇게 코드를 수정해서 한 번 돌려 보시고 피드백 남겨 주셨으면 좋겠네요^^
정상 동작한다면 원본 코드에 수정사항 반영하도록 하겠습니다!
@chj2812  님 코드 공유 감사합니다!

**Comment by normalstory** [comment]
@chj2812 오~ 고맙습니다!! 
덕분에 관련 부분을 주석처리 해보니 chat 기능은 동작하는 것으로 확인할 수 있었습니다!! 

덕분에 힌트를 얻어,,,, 추정컨데 
app/chain.py에서는 variable_name, 
app/server.py에서는 러너블과 뤵스뮈쓰 설정 관련된 내용이었던 것 같습니다;; 

제가 요즘 이사 준비로 정신이 없어서 시간을 많이 못 내고 있어서;;; 속도가 좀 더디네요 ㅜ 
조금 더 속도를 내서 한꼬집 더 살펴보도록 하겠습니다~

**Comment by normalstory** [comment]
https://github.com/langchain-ai/langserve/issues/613#issuecomment-2077015322

랭서브 깃헙에 이슈를 달았더니 답변을 받았습니다. langserve 0.1.0 버그였다고 하고요~ Patched release 0.1.1 해주셨습니다~
`pip install langserve==0.1.1` 하신 후 다시 실행하시면 테디님 코드 모두(& LangSmith link) 정상적으로 작동합니다~ 

<img width="1127" alt="스크린샷 2024-04-26 오전 1 26 03" src="https://github.com/teddylee777/langserve_ollama/assets/1615995/ff97e206-ef55-40e6-9eb2-8192f4024b5f">
<img width="1439" alt="스크린샷 2024-04-26 오전 1 26 13" src="https://github.com/teddylee777/langserve_ollama/assets/1615995/58ba90c6-a63a-4ade-962c-36ef26405b24">

**Comment by teddylee777** [comment]
@normalstory 님 정말 고생 많으셨어요!
LangServe 공식 깃헙에도 기여를 하셨네요!
드디어 깔끔하게 해결된 스크린샷을 보니 제가 다 마음이 편안해 지네요~^^
이 이슈는 곧 닫겠습니다! 이슈 남겨주시고 직접 해결도 해주셔서 감사드립니다!

**Comment by normalstory** [comment]
@teddylee777 님 덕분에 좋은 경험할 수 있었습니다! 고맙습니다!! 앞으로도 테디님 따라서 열혈'열Lang' 하겠습니다~ 😍
