### ISSUE TITLE
xionic.py 파일의 base_url 문의

### ISSUE THREAD

**Issue by bigsea00001** [teddylee777/langserve_ollama#3]
base_url="http://sionic.chat:8001/v1", 이렇게 되어 있는데, 이것 때문인지는 몰라도 답변은 잘 하는데, 제 gpu 사용률은 전혀 안 움직이는데요??
그리고 이 코드 밑에 api_key와 model 명이 있는데 이것은 어떻게 해야 할 지 모르겠습니다 ㅠ

**Comment by teddylee777** [comment]
네 말씀하신 것 처럼 `base_url="http://sionic.chat:8001/v1"` 이 코드는 외부 모델을 사용하는 코드이고요. 로컬 모델로 바꿔주셔야 자신의 PC 에 있는 모델을 구동하게 됩니다.
xionic.py 는 sionic-ai 회사의 모델을 사용하는 거에요.
로컬 PC 에서 구동하는 ollama 모델을 사용하는 방법은 llm.py 나 chat.py, 00-ollama-test.ipynb 파일을 참고해 주세요!

**Comment by bigsea00001** [comment]
감사합니다~ 해결되었습니다^^!
